// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eBikeSystem.Entities;

public partial class PurchaseOrderDetail
{
    [Key]
    [Column("PurchaseOrderDetailID")]
    public int PurchaseOrderDetailId { get; set; }

    [Column("PurchaseOrderID")]
    public int PurchaseOrderId { get; set; }

    [Column("PartID")]
    public int PartId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal PurchasePrice { get; set; }

    [StringLength(50)]
    public string VendorPartNumber { get; set; }

    [ForeignKey("PartId")]
    [InverseProperty("PurchaseOrderDetails")]
    public virtual Part Part { get; set; }

    [ForeignKey("PurchaseOrderId")]
    [InverseProperty("PurchaseOrderDetails")]
    public virtual PurchaseOrder PurchaseOrder { get; set; }

    [InverseProperty("PurchaseOrderDetail")]
    public virtual ICollection<ReceiveOrderDetail> ReceiveOrderDetails { get; set; } = new List<ReceiveOrderDetail>();

    [InverseProperty("PurchaseOrderDetail")]
    public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; } = new List<ReturnedOrderDetail>();
}