// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eBikeSystem.Entities;

public partial class ReceiveOrder
{
    [Key]
    [Column("ReceiveOrderID")]
    public int ReceiveOrderId { get; set; }

    [Column("PurchaseOrderID")]
    public int PurchaseOrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ReceiveDate { get; set; }

    [Column("EmployeeID")]
    public int EmployeeId { get; set; }

    [ForeignKey("PurchaseOrderId")]
    [InverseProperty("ReceiveOrders")]
    public virtual PurchaseOrder PurchaseOrder { get; set; }

    [InverseProperty("ReceiveOrder")]
    public virtual ICollection<ReceiveOrderDetail> ReceiveOrderDetails { get; set; } = new List<ReceiveOrderDetail>();

    [InverseProperty("ReceiveOrder")]
    public virtual ICollection<ReturnedOrderDetail> ReturnedOrderDetails { get; set; } = new List<ReturnedOrderDetail>();
}