// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eBikeSystem.Entities;

[Index("SaleId", "PartId", Name = "UQ_SaleDetails_SaleIDPartID", IsUnique = true)]
public partial class SaleDetail
{
    [Key]
    [Column("SaleDetailID")]
    public int SaleDetailId { get; set; }

    [Column("SaleID")]
    public int SaleId { get; set; }

    [Column("PartID")]
    public int PartId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "money")]
    public decimal SellingPrice { get; set; }

    [ForeignKey("PartId")]
    [InverseProperty("SaleDetails")]
    public virtual Part Part { get; set; }

    [ForeignKey("SaleId")]
    [InverseProperty("SaleDetails")]
    public virtual Sale Sale { get; set; }
}