// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eBikeSystem.Entities;

public partial class Vendor
{
    [Key]
    [Column("VendorID")]
    public int VendorId { get; set; }

    [Required]
    [StringLength(100)]
    public string VendorName { get; set; }

    [Required]
    [StringLength(12)]
    public string Phone { get; set; }

    [Required]
    [StringLength(30)]
    public string Address { get; set; }

    [Required]
    [StringLength(30)]
    public string City { get; set; }

    [Required]
    [Column("ProvinceID")]
    [StringLength(2)]
    [Unicode(false)]
    public string ProvinceId { get; set; }

    [Required]
    [StringLength(6)]
    public string PostalCode { get; set; }

    [InverseProperty("Vendor")]
    public virtual ICollection<Part> Parts { get; set; } = new List<Part>();

    [InverseProperty("Vendor")]
    public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; } = new List<PurchaseOrder>();
}